name: Documentation Update
description: Suggest improvements to documentation
title: "[Docs]: "
labels: ["documentation"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping improve our documentation!

  - type: dropdown
    id: doc-type
    attributes:
      label: Documentation Type
      description: What type of documentation needs improvement?
      options:
        - Function help (comment-based or markdown)
        - README.md
        - CONTRIBUTING.md
        - Code comments
        - Examples
        - Other
    validations:
      required: true

  - type: textarea
    id: location
    attributes:
      label: Location
      description: Where is the documentation issue located?
      placeholder: |
        - File/Function: [e.g., .src/Public/Get-PSScriptModuleInfo]
        - Section: [e.g., EXAMPLES]
    validations:
      required: true

  - type: textarea
    id: issue
    attributes:
      label: Issue Description
      description: What is wrong or missing in the current documentation?
      placeholder: Describe the documentation issue
    validations:
      required: true

  - type: textarea
    id: suggestion
    attributes:
      label: Suggested Improvement
      description: How would you improve the documentation?
      placeholder: Provide your suggested changes or additions
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context or examples
