name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide as much detail as possible.

  - type: textarea
    id: summary
    attributes:
      label: Feature Summary
      description: A brief description of the feature you'd like to see
      placeholder: What feature would you like to add?
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: Describe the problem or limitation you're facing
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like this feature to work?
      placeholder: Describe your ideal solution
    validations:
      required: true

  - type: textarea
    id: example
    attributes:
      label: Usage Example
      description: Provide an example of how this feature would be used
      placeholder: |
        ```powershell
        # Example usage
        Get-Something -NewParameter Value
        ```
      render: powershell

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What alternative solutions or workarounds have you considered?
      placeholder: Describe any alternative approaches

  - type: dropdown
    id: breaking
    attributes:
      label: Breaking Change
      description: Would this be a breaking change?
      options:
        - "No"
        - "Yes"
        - "Not sure"
    validations:
      required: true

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Are you willing to contribute to this feature?
      options:
        - label: I am willing to submit a pull request for this feature

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or references about the feature request
